### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Fil** [Fil/d3-geo-voronoi#1]
Loren Petrich's lib uses an algorithm that seems to be in `O(n^2)`. It is unpractical for n > 1000. (d3-voronoi runs in `O(n) log(n)`.)

See http://bl.ocks.org/Fil/704bdbac80ab2e5d741d5fa3662bdf82

Three possibilities:
- 1) “I'm sorry, Dave, I'm afraid I can't do that”: let geoVoronoi() log a warning if n > 500 (10s on my computer) and return an error if n > 2000 (2.5 min).
- 2) Switch to an approximate algorithm when n > 500 (If we accept bugs around the poles, we can piggy-back on d3-voronoi by using a specific cylindric projection.)
- 3) Find and implement a better algorithm.

**Comment by Fil** [comment]
See if we can apply the sweep-hull technique of https://github.com/mapbox/delaunator / https://github.com/d3/d3-delaunay to our 3D model. Or use D. Sinclair's newer algorithm https://arxiv.org/pdf/1602.04707.pdf

**Comment by Fil** [comment]
Here's a notebook that seems to work, built on top of d3-delaunay. https://beta.observablehq.com/@fil/geo-delaunay

Computations are several orders of magnitude faster than the current d3-geo-voronoi.

(The notebook is not that fast, because rendering is slow.)

**Comment by Fil** [comment]
Do you mean when n is small? This should be fixed now — in the sense that the code shouldn't break anymore when n <= 3.

I'm still working on the n=3 case to build the correct polygons (LineStrings connecting antipodal points… that doesn't work well).

**Comment by mbostock** [comment]
I think I just borked something in my simplification of your code. I switched to importing your notebook directly (using `with {points}` to replace the input) and it works great!

**Comment by Fil** [comment]
My code from yesterday was not working that well :-) There are quite a bit of difficult issues when n is small and the points are clumped together in one spot.

**Comment by mbostock** [comment]
I added a mesh computation to my notebook, too.

**Comment by Fil** [comment]
In terms of capacity, it looks like the maximum on my computer is n = 125578 points. The polygons are still computed in a few seconds.

I don't know why it breaks with n = 125579, observable catches the error and the console does not report. Not d3-delaunay's fault, it can go much higher than that (10 million points and more).

**Comment by Fil** [comment]
I just published release 1.0.0 based on d3-delaunay (wooohooo)
