### ISSUE TITLE
No geoContour in v1.6.0 release.

### ISSUE THREAD

**Issue by nemo9955** [Fil/d3-geo-voronoi#17]
https://github.com/Fil/d3-geo-voronoi/releases

**Comment by nemo9955** [comment]
Inside d3-geo-voronoi/d3-geo-voronoi.js :

// https://github.com/Fil/d3-geo-voronoi **Version 1.2.1**. Copyright 2019 Philippe Rivière.

**Comment by Fil** [comment]
I've fixed the zip file, thank you!

(of course I have no idea how I managed to put an old file in a release! 😱)
