### ISSUE TITLE
Would pull requests with typescript *.d.ts definition files be welcome

### ISSUE THREAD

**Issue by martinfrances107** [Fil/d3-geo-voronoi#19]
Hi I love this module.. I am happily using it

There is one fly in the ointment.

I am using it in a typescript project. 

Currently that mean I need to fake the index.d.ts files so I can invoke this in *.ts and *.tsx files.

`import { geoVoronoi } from 'd3-geo-voronoi';`

If I create the relevant files would you review and maybe merge my work?

It would be a big task ... so I just want to check before I do anything?

**Comment by Fil** [comment]
I'm following https://github.com/d3/d3/issues/3351#issuecomment-539522081 in this and defer to https://www.npmjs.com/package/@types/d3 ; however if your code review for this shows that things must be changed here, I will happily accept a PR.
