### ISSUE TITLE
Benchmarks: A uniform approach

### ISSUE THREAD

**Issue by martinfrances107** [Fil/d3-geo-voronoi#28]
I am getting into position where I need to start running comparative performance test between this module and my port to rust.

What is missing from this project is a standardised set of benchmarks which I can also port.

With a public module what I am concerned about is two stakeholders with different code-bases depending on this "library"

For a given PR one stakeholder can see a improvement whilst the other sees a degradation in performance.

The solution is to have a comprehensive set of samples with a diverse set of possible example uses.

Then we can make balanced judgements.

Philippe Rivière. [ hi :)  ] has provided a high quality sample which I suggest we start using 

https://bl.ocks.org/Fil/raw/a9ba8d0d023752aa580bd95480b7de60/

it is a rotating sphere onto which a 50 points are mapped.

a) The FPS from a browser can be used as a measure of goodness
b) Time to first paint can be used to track how long it takes to ingest a number of points.

I want to include in this webpage in a "benchmark" directory

but ... which pulls in the contents of the dist directory

For comparison I want to add buttons so we can compare the FPS for 50, 500,  5,000, 50,000 points.
[ 50,000 points ... I know I can dream... but I think 6000 points from the rust port is doable ]

If other readers can suggest other code samples which will challenge the library in alternative ways then we can add to the directory.

Anyway I will post a PR later this weekend

**Comment by Fil** [comment]
closed by #29
